naprawa

diff --git a/.github/workflows/github-actions-demo.yml b/.github/workflows/github-actions-demo.yml
--- a/.github/workflows/github-actions-demo.yml
+++ b/.github/workflows/github-actions-demo.yml
@@ -14,7 +14,7 @@ jobs:
       - name: Display Python version
         run: python -c "import sys; print(sys.version)"
 
-  lint-application:
+  test-application:
     runs-on: ubuntu-latest
     needs: check-python-version
     steps:
@@ -23,7 +23,23 @@ jobs:
         uses: actions/setup-python@v2
         with:
           python-version: '3.8'
-      - name: Install Pylint
-        run: pip install pylint
-      - name: Run Pylint
-        run: pylint app.py
+      - name: Install dependencies
+        run: |
+          python -m venv venv
+          source venv/bin/activate
+          pip install -r requirements.txt
+      - name: Run Flask app
+        run: |
+          nohup python app.py &
+          sleep 5  # gives Flask time to start
+      - name: Check if Flask app is up and displays the correct message
+        run: |
+          response=$(curl -s http://localhost:5000/)
+          echo "Server response: $response"
+          if [[ "$response" == *'Hello WSB! Greetings from Flask!'* ]]; then
+            echo "Response test passed"
+          else
+            echo "Response test failed"
+            exit 1
+
+
